// Integer division by a small run-time divisor, without a software divide call
//
// Copyright (C) 2026 Pono Data Solutions
//
// This file may be distributed under the terms of the GNU GPLv3 license.

#ifndef __SMALL_DIVIDE_H__
#define __SMALL_DIVIDE_H__

#include <stdint.h>

// AVR and Cortex-M0 have no divide instruction, so any run-time `/` or `%` on a
// 32-bit type links a libgcc helper: __divmodsi4 on AVR, __divsi3 on Cortex-M0.
// scripts/check-software-div.sh rejects an image carrying one, because those
// helpers are a bit-at-a-time loop and these call sites are in a sensor hot
// path. Both cores do have a multiplier, so a reciprocal multiply is both
// allowed and faster.
//
// udiv_small and sdiv_small return exactly what `/` returns, including
// truncation toward zero on a negative dividend, for divisors 1 through
// SMALL_DIVIDE_MAX. That is not an estimate: scripts/verify-small-divide.c
// compares them against the native operators for every one of the 2^32 unsigned
// and 2^32 signed dividends, on every divisor in range.
//
// A divisor outside 1..SMALL_DIVIDE_MAX reads past the table, so the caller
// must bound it. Every current caller divides by a sliding-window or sensor
// count that is fixed at config time and capped well below the limit.

#define SMALL_DIVIDE_MAX 16

struct small_divide_entry {
    uint32_t m;         // reciprocal; zero means the divisor is a power of two
    uint8_t add;        // needs the 33-bit overflow correction step
    uint8_t s;          // final right shift
};

// Generated by scripts/gen-small-divide.py. Do not hand-edit; regenerate.
static const struct small_divide_entry small_divide_tab[SMALL_DIVIDE_MAX + 1] = {
    {          0u, 0,  0 },  //  0  unused
    {          0u, 0,  0 },  //  1  shift
    {          0u, 0,  1 },  //  2  shift
    { 2863311531u, 0,  1 },  //  3
    {          0u, 0,  2 },  //  4  shift
    { 3435973837u, 0,  2 },  //  5
    { 2863311531u, 0,  2 },  //  6
    {  613566757u, 1,  2 },  //  7  add form
    {          0u, 0,  3 },  //  8  shift
    {  954437177u, 0,  1 },  //  9
    { 3435973837u, 0,  3 },  // 10
    { 3123612579u, 0,  3 },  // 11
    { 2863311531u, 0,  3 },  // 12
    { 1321528399u, 0,  2 },  // 13
    {  613566757u, 1,  3 },  // 14  add form
    { 2290649225u, 0,  3 },  // 15
    {          0u, 0,  4 },  // 16  shift
};

static inline uint32_t
udiv_small(uint32_t v, uint32_t d)
{
    const struct small_divide_entry *e = &small_divide_tab[d];
    if (!e->m)
        return v >> e->s;
    uint32_t t = (uint32_t)(((uint64_t)v * e->m) >> 32);
    if (e->add)
        // The exact reciprocal needs 33 bits. Folding the carry in this way
        // keeps every intermediate inside 32 bits.
        t += (v - t) >> 1;
    return t >> e->s;
}

static inline int32_t
sdiv_small(int32_t v, uint32_t d)
{
    uint32_t u = (v < 0) ? (uint32_t)0 - (uint32_t)v : (uint32_t)v;
    uint32_t q = udiv_small(u, d);
    return (v < 0) ? (int32_t)((uint32_t)0 - q) : (int32_t)q;
}

// Divisors above SMALL_DIVIDE_MAX get their own constant. A compile-time
// divisor is no help on these cores: gcc still calls libgcc for anything that
// is not a power of two. Magic from scripts/gen-small-divide.py, checked the
// same exhaustive way as the table.
static inline int32_t
sdiv_10000(int32_t v)
{
    uint32_t u = (v < 0) ? (uint32_t)0 - (uint32_t)v : (uint32_t)v;
    uint32_t q = (uint32_t)(((uint64_t)u * 3518437209u) >> 32) >> 13;
    return (v < 0) ? (int32_t)((uint32_t)0 - q) : (int32_t)q;
}

#endif // __SMALL_DIVIDE_H__
